## 1. Create a 1-D array of integers from 0 to 9 and then reverse it.


In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
print("Original Array:", arr)

Original Array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
reversed_arr=arr[::-1]

In [5]:
print("Reversed Array:", reversed_arr)

Reversed Array: [9 8 7 6 5 4 3 2 1 0]


## 2. Create a 3x3 matrix with values ranging from 0 to 8 and find the determinant of the matrix.


In [6]:
matrix=np.arange(9).reshape(3,3)

In [7]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
determinant=np.linalg.det(matrix)

In [9]:
print(determinant)

0.0


## 3. Create a 5x5 matrix with random values between 0 and 1, and then find the minimum and maximum values of the matrix.


In [10]:
# Create a 5x5 matrix with random values between 0 and 1. 
value=np.random.rand(5,5)

In [11]:
# Find the minimum value of the matrix
print(value.min())

0.030824889631834718


In [12]:
# Find the maximum value of the matrix
print(value.max())

0.924128969175633


## 4. Create a 4x4 matrix with values ranging from 0 to 15 and reshape it to a 2x8 matrix.


In [13]:
# Create a 4x4 matrix ranging from 0-15
matrix=np.random.randint(0,15,(4,4))

In [14]:
print(matrix)

[[ 9  8 11  7]
 [11 14 12  7]
 [ 5 14 11  5]
 [12  3 11 13]]


In [15]:
# Reshaping it into 2x8 matrix
new_matrix=matrix.reshape(2,8)

In [16]:
print(new_matrix)

[[ 9  8 11  7 11 14 12  7]
 [ 5 14 11  5 12  3 11 13]]


## 5. Create a 1-D array of 10 random integers between 1 and 100, and then find the mean, median, and standard deviation of the array.

In [17]:
# Generate a random integers from 10 to 100
arr=np.random.randint(1,101,(10))

In [18]:
print(arr)

[77 64 54 62 54 33 30 49 18 40]


In [19]:
# Calculating Mean
print(np.mean(arr))

48.1


In [20]:
# Calculating median
print(np.median(arr))

51.5


In [21]:
# Calculating standard deviation
print(np.std(arr))

16.967321532876074


## 6. Create a 2-D array with values ranging from 0 to 8 and extract the second and third rows of the array.

In [22]:
# Creating a 2-d array
arr=np.arange(9).reshape(3,3)

In [23]:
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Extrating the second and third rows
print(arr[1:3,:])

[[3 4 5]
 [6 7 8]]


In [25]:
# Extracting the first and last columns
print(arr[:,[0,2]])

[[0 2]
 [3 5]
 [6 8]]


## 7. Create a 2-D array with values ranging from 0 to 15 and extract every other element of the array using slicing.

In [27]:
arr=np.arange(16).reshape(4,4)

In [28]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
# Extracting every other elements using slicing
print(arr[::3,::2])

[[ 0  2]
 [12 14]]


## 8. Create a 2-D array with values ranging from 0 to 15 and divide each element of the array by 2.

In [32]:
arr=np.arange(16).reshape(4,4)

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
# Dividing each element of the array by 2
print(arr/2)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]
 [6.  6.5 7.  7.5]]


## 9. Create a 2-D array with values ranging from 0 to 15 and find the sum of all the elements of the array.

In [35]:
arr=np.arange(16).reshape(4,4)

In [36]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
# Getting sum of all elements of the array
print(np.sum(arr))

120


## 10. Create a 2-D array with values ranging from 0 to 15 and find the transpose of the array.


In [41]:
arr=np.arange(16).reshape(4,4)

In [42]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
# Transposing the matrix
print(np.transpose(arr))

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
